CREATE TABLE PROJECTS (
  PROJECT_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(128) UNIQUE
);

CREATE TABLE MAPS (
  MAP_ID SERIAL PRIMARY KEY,
  PROJECT_ID BIGINT,
  NAME VARCHAR(128),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID) ON DELETE CASCADE
);

CREATE TABLE  SCANS  (
  WIFI_SCAN_ID SERIAL PRIMARY KEY,
  MAC_ADDRESS VARCHAR(64) NOT NULL,
  DEVICE_NAME VARCHAR(64),
  LATITUDE  DOUBLE PRECISION,
  LONGITUDE  DOUBLE PRECISION,
  ALTITUDE  DOUBLE PRECISION,
  LOCATION_RES  DOUBLE PRECISION,
  GEOMAG_X  DOUBLE PRECISION,
  GEOMAG_Y  DOUBLE PRECISION,
  GEOMAG_Z  DOUBLE PRECISION,
  GEOMAG_RES  DOUBLE PRECISION,
  ACCEL_X  DOUBLE PRECISION,
  ACCEL_Y  DOUBLE PRECISION,
  ACCEL_Z  DOUBLE PRECISION,
  ACCEL_RES  DOUBLE PRECISION,
  COORD_X  DOUBLE PRECISION NOT NULL,
  COORD_Y  DOUBLE PRECISION,
  DEVICE_TIME BIGINT,
  NTP_TIME BIGINT,
  MAP_ID BIGINT,
  PROJECT_ID BIGINT,
  ROTATION_MATRIX CHAR(128),
  FOREIGN KEY (MAP_ID) REFERENCES MAPS(MAP_ID) ON DELETE CASCADE,
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID) ON DELETE CASCADE
);

CREATE TABLE WIFI_SCANS (
  WIFI_SCAN_ID SERIAL,
  BSSID VARCHAR(128),
  LEVEL INTEGER,
  FREQUENCY BIGINT,
  FOREIGN KEY (WIFI_SCAN_ID) REFERENCES SCANS(WIFI_SCAN_ID) ON DELETE CASCADE,
  PRIMARY KEY (WIFI_SCAN_ID, BSSID)
);

CREATE TABLE NEURAL_NETS (
  NETWORK_ID SERIAL,
  BSSID VARCHAR(128),
  FOREIGN KEY (NETWORK_ID) REFERENCES NETS_DATA(NETWORK_ID) ON DELETE CASCADE,
);

CREATE TABLE NETS_DATA (
  NETWORK_ID SERIAL,
  MAP_ID SERIAL,
  NETWORK_DATA BYTEA,
  FOREIGN KEY (MAP_ID) REFERENCES MAPS(MAP_ID) ON DELETE CASCADE,
  PRIMARY KEY NETWORK_ID
);


